---
##  Launching of our hosts to orchetrate against ##
- name: Spin up hosts to orchestrate
  hosts: localhost
  gather_facts: false

  vars:
    ec2_region: us-west-1
    count: 1
    security_group: lamp_stack
    image: ami-ac5f2fcc
    type: t2.micro

  tasks:
  - name: Launch a webserver ec2 instance to work on!
    ec2:
      keypair: bcoursen
      group: "{{ security_group }}"
      image: "{{ image }}"
      type: "{{ type }}"
      region: "{{ ec2_region }}"
      instance_tags:
          Name: "lamp"
          server: "webservers"
      count: "{{ count }}"
      wait: true
    register: ec2
  - debug:
      msg: "{% set comma = joiner(',') %}
            {% for host in ec2.instances -%}
                '{{ comma() }}{{ host.dns_name }}'
            {%- endfor %}"
  - name: Launch a dbserver ec2 instance to work on!
    ec2:
      keypair: bcoursen
      group: "{{ security_group }}"
      image: "{{ image }}"
      type: "{{ type }}"
      region: "{{ ec2_region }}"
      instance_tags:
          Name: "lamp"
          server: "dbservers"
      count: "{{ count }}"
      wait: true
