---
- name: Let's test debug
  hosts: all
  tasks:
    - name: Shell
      shell: /usr/bin/uptime
      register: result

    - name: Here's our output
      fail: msg={{ result.stdout }}
      ignore_errors: true
