---
- name: Let's test debug
  hosts: all
  tasks:
    - name: create/launch
      ec2:
        instance_type: {{instance_type}}
        image: {{image}}
        wait: true
        region: {{region}}
        count: {{count}}
        keypair: {{keyname}}
        group: dsilva-test
      register: ec2

    - name: tag it
      ec2_tag:
        resource: {{ item.id }}
        region: {{ region }}
        state: present
      with_items: ec2.instances
      args:
        tags:
          Name: "{{id_base}}-{{item.id}}"

    - name: create output
      debug:
        msg: "{% set comma = joiner(',') %}
              {% for host in ec2.instances -%}
                  "{{ comma() }}{{ host.dns_name }}"
              {%- endfor %}"
