---
- name: Let's test debug
  hosts: localhost
  gather_facts: false

  vars:
    region: us-west-2
    count: 1

  tasks:
  - name: create/launch
    ec2:
      keypair: dsilva
      group: dsilva-demo
      image: ami-5189a661
      instance_type: t2.micro
      region: "{{ region }}"
      instance_tags:
          Name: "dsilva_demo"
      count: "{{ count }}"
      wait: true
    register: ec2

    - name: tag it
      ec2_tag:
        resource: {{ item.id }}
        region: {{ region }}
        state: present
      with_items: ec2.instances
      args:
        tags:
          Name: "{{ id_base }}-{{ item.id }}"

    - name: create output
      debug:
        msg: "{% set comma = joiner(',') %}
              {% for host in ec2.instances -%}
                  "{{ comma() }}{{ host.dns_name }}"
              {%- endfor %}"
