---
- name: Prep for class
  hosts: all
  tasks:
    - name: Install packages
      yum: name={{ item }} state=latest
      with_items:
        - python-setuptools
        - python-devel
        - gcc
        - git
      become: true
    - name: Install pip
      easy_install: name=pip
      become: true
    - name: remove already installed deps
      yum: name=python-crypto state=absent
      become: true
    - name: Install ansible deps
      pip: name={{ item }} state=latest
      with_items:
        - paramiko
        - PyYAML
        - Jinja2
        - httplib2
        - six
        - ansible
      become: true
    - name: checkout playbook repo
      git: repo=git@github.com:justnems/ansible-demo-examples.git
           dest=/home/ec2-user
           key_file=/home/ec2_user/.ssh/soluteTraining.pem
           accept_hostkey=yes
