---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: false

  vars:
    region: us-west-2
    count: 1
    group: Production

  tasks:
  - name: Launch!
    ec2:
      keypair: dsilva
      group: dsilva-demo
      image: ami-5189a661
      type: t2.micro
      region: "{{ region }}"
      instance_tags:
          Name: "dsilva_demo"
      count: "{{ count }}"
      wait: true
    register: ec2
  - name: Add launched to group.
    add_host: hostname={{ item.public_ip }} groupname={{ group }}
    with_items: ec2.instances
