---
- hosts: localhost
  gather_facts: false

  vars:
    region: us-west-2
    count: 1

  tasks:
  - name: Launch a couple of ec2 instances to work on!
    ec2:
      keypair: dsilva
      group: dsilva-demo
      image: ami-5189a661
      type: t2.micro
      region: "{{ region }}"
      instance_tags:
          Name: "dsilva_demo"
      count: "{{ count }}"
      wait: true
