---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: false

  vars:
    region: us-west-2
    count: 1
    group: Production

  tasks:
  - name: Launch!
    ec2:
      keypair: dsilva
      group: dsilva-demo
      image: ami-5189a661
      type: t2.micro
      region: "{{ region }}"
      instance_tags:
          Name: "dsilva_demo"
          env: "Production"
      count: "{{ count }}"
      wait: true
