---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: false

  vars:
    region: us-west-1
    env: Production
    image: ami-d1315fb1
    count: 1

  tasks:
  - name: Launch!
    ec2:
      keypair: bcoursen
      group: launch-wizard-2
      image: "{{ image }}"
      type: t2.micro
      region: "{{ region }}"
      instance_tags:
          Name: "brian"
          server: spinup
      count: "{{ count }}"
      wait: true
