- name: Launch Windows Instance
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    - group_vars/windows_spinup

  vars:
    ec2_region: us-west-1
    count: 1
    security_group: windows
    image: ami-afbff1cf
    type: t2.micro
    ansible_winrm_server_cert_validation: ignore
    name: brian
    server: windows
    role: conf

 # Launch instances with the following parameters.  Register the output.
  tasks:
    - name: Launch instance
      local_action:
        module: ec2
        region: "{{ec2_region}}"
        image: "{{image}}"
        instance_type: "{{type}}"
        group: "{{security_group}}"
        key_name: "bcoursen"
        instance_tags:
          Name: "{{name}}"
          server: "{{server}}"
          role: "{{role}}"
        count: "{{count}}"
