---
- name: Install packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=installed"
  with_items:
    - vim
    - net-tools
    - screen
    - iptraf
    - wireshark
    - nmap
    - sysstat

# - name: Update all packages
#   yum: name=* state=latest
